_prompt_template: &_prompt_template |
  You are tasked with creating a rule book for a new single-player {{ values[0] }} designed to be played in a command-line interface. The game should be easy and simple to code, with clear success/failure conditions and should be solvable within a reasonable number of moves. Furthermore, the game should be designed to have multiple difficulty levels and require strategic thinking to solve efficiently. Make sure that the game is unique, and is NOT similar to existing games such as Sokoban, Sliding Puzzle, 2048, or Tetris. The rule book should cover the following aspects:
  Objective: Clearly define the primary goal of the game. Explain how the player can achieve victory and what constitutes success or failure.
  Setup: Describe the initial setup of the game, including the arrangement of game elements, player starting position, and any starting conditions. Include how different difficulty levels are configured.
  Game Components: List and explain all components involved in the game, such as tiles, objects, obstacles, or collectibles. Provide details on their appearance, functionality, and any unique attributes.
  Actions: Outline the available actions the player can take, including movement, interaction with objects, special abilities, and how actions affect the game state.
  Rules and Mechanics: Detail the core rules and mechanics of the game. This should include movement rules, object interactions, environmental effects, constraints, and any unique game mechanics that create puzzle-solving challenges.
  Scoring: Explain how performance is measured, such as move count, time limits, bonus points for efficiency, or other metrics that encourage optimal play.
  Win/Lose Conditions: Clearly define success conditions (puzzle solved) and failure conditions (if any), including any time limits or move restrictions.
  Examples: Provide example scenarios and command-line interactions showing initial state, sample moves, and progression toward the solution to illustrate how the rules are applied in practice.
  Ensure that the rule book is clear, organized, and comprehensive, providing all necessary information to players while creating engaging puzzle-solving challenges with strategic depth.
prompts:
  - !jinja2 [*_prompt_template, "exploration game"]
  # - !jinja2 [*_prompt_template, "interactive environment"]
  # - !jinja2 [*_prompt_template, "game"]
  # - !jinja2 [*_prompt_template, "game"]
  # - !jinja2 [*_prompt_template, "card game"]
  # - !jinja2 [*_prompt_template, "word game"]
  # - !jinja2 [*_prompt_template, "number game"]
  # - !jinja2 [*_prompt_template, "abstract strategy game"]
model: o3
# max_completion_tokens: 4096
max_completion_tokens: 4096
num_games: 1



