instruction_prompt: |
  Here is a description for a two-player game:
  <GameDescription>

  You will be prompted with a board state and a list of legal moves for the current play. Your task is to pick the best move from this list. Here is a description for what each move represents:
  <MoveDescription>
turn_prompt: |
  <BoardState>
  Legal moves: <LegalMoves>
  Pick the best move from the list of legal moves. Respond with the number you wish to play. Do not include any other text in your response.
num_games_per_env: 30
max_turns_per_game: 100
